Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 11

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassVars:
  Enabled: false
